### ISSUE TITLE
Server failing to start due to 403 returned by StopModsRepost API

### ISSUE THREAD

**Issue by TigerWalts** [TerraFirmaCraft-The-Final-Frontier/FileDirector#11]
FileDirector 1.7.0
Modpack Magiculture 2 - 0.8.7.3

Downloads are failing due to the request to https://api.stopmodreposts.org/sites.json returning a `403`.

Adding the mods manually will prevent any download attempts and allows the server to start.

<details>
  <summary>Error in server log</summary>

```
[12:14:03] [main/INFO] [ModDirector/ConfigurationController[CORE]]: Loading config config/mod-director/serializationisbad.url.json
[12:14:03] [pool-2-thread-2/ERROR] [ModDirector/InstallController[CORE]]: Failed to install mod /dogboy21/serializationisbad/releases/download/1.3/serializationisbad-1.3.jar
net.jan.moddirector.core.exception.ModDirectorException: Failed to retrieve StopModReposts database
	at net.jan.moddirector.core.manage.check.StopModReposts.initialize(StopModReposts.java:72) ~[StopModReposts.class:1.7.0-SNAPSHOT]
	at net.jan.moddirector.core.manage.check.StopModReposts.check(StopModReposts.java:28) ~[StopModReposts.class:1.7.0-SNAPSHOT]
	at net.jan.moddirector.core.configuration.type.UrlRemoteMod.performInstall(UrlRemoteMod.java:108) ~[UrlRemoteMod.class:1.7.0-SNAPSHOT]
	at net.jan.moddirector.core.manage.install.InstallableMod.performInstall(InstallableMod.java:36) ~[InstallableMod.class:1.7.0-SNAPSHOT]
	at net.jan.moddirector.core.manage.InstallController.handle(InstallController.java:282) ~[InstallController.class:1.7.0-SNAPSHOT]
	at net.jan.moddirector.core.manage.InstallController.lambda$createInstallTasks$1(InstallController.java:254) ~[InstallController.class:1.7.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.stopmodreposts.org/sites.json
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_312]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1947) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1942) ~[?:1.8.0_312]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1941) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1511) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1487) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1485) ~[?:1.8.0_312]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_312]
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1484) ~[?:1.8.0_312]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_312]
	at net.jan.moddirector.core.util.WebClient.get(WebClient.java:58) ~[WebClient.class:1.7.0-SNAPSHOT]
	at net.jan.moddirector.core.manage.check.StopModReposts.initialize(StopModReposts.java:63) ~[StopModReposts.class:1.7.0-SNAPSHOT]
	... 9 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.stopmodreposts.org/sites.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1897) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1487) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1485) ~[?:1.8.0_312]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_312]
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1484) ~[?:1.8.0_312]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_312]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352) ~[?:1.8.0_312]
	at net.jan.moddirector.core.util.WebClient.get(WebClient.java:24) ~[WebClient.class:1.7.0-SNAPSHOT]
	at net.jan.moddirector.core.manage.check.StopModReposts.initialize(StopModReposts.java:63) ~[StopModReposts.class:1.7.0-SNAPSHOT]
	... 9 more
```

</details>

Modpack client downloads the `sites.json` OK.

```
[17:09:16] [main/INFO] [ModDirector/ConfigurationController[CORE]]: Loading config config\mod-director\serializationisbad.url.json
[17:09:18] [pool-2-thread-2/INFO] [ModDirector/InstallController[CORE]]: Installed mod file C:\Users\Stuart\curseforge\minecraft\Instances\Magiculture 2\mods\serializationisbad-1.3.jar
```

<details>
  <summary>Downloading the file using cURL and a User-Agent responds with a page requiring javascript and cookies</summary>

```console
# curl -H "User-Agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" https://api.stopmodreposts.org/sites.json
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/cdn-cgi/styles/challenges.css" rel="stylesheet"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span class="icon-wrapper"><div class="heading-icon warning-icon"></div></span><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '2',cZone: "api.stopmodreposts.org",cType: 'managed',cNounce: '11217',cRay: '8192682249015401',cHash: '974c8c741a1850e',cUPMDTk: "\/sites.json?__cf_chl_tk=dljFysk7cAadUlg75wtmdChvFU9LSp_ViLbexJquVXQ-1697816924-0-gaNycGzNCvs",cFPWv: 'b',cTTimeMs: '1000',cMTimeMs: '0',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "\/sites.json?__cf_chl_f_tk=dljFysk7cAadUlg75wtmdChvFU9LSp_ViLbexJquVXQ-1697816924-0-gaNycGzNCvs",md: "tIdBPL.C.PGAyYPoFDO9SiFeEU7Q44SPbnD6sjnv.7s-1697816924-0-AcDlU7uNXs9XqH2f1BIZ0-Ejp1Hrj5JPCExarMA5uepJNwh746EkjZChoEOpIG27BFXOBRdiAsl6Shd1X-G2z05F-np5nHbIMoYaD5Pp8sze-axdn6srJYqYslxWv4oFPWDDv53nws-o4Qg-e8SOwUzsHJLVJMGg-T1Y7A397i7yaw8lCw5wu93srACstVyNn6iYIJShs1r8Ue9dyGHtnAdZdZGzF9ptn6Q9PEoCf2U-FqC_yny8DC32y08wtbOZJzjaHBhzlvqi78BOXif51Tb22drtQBxBD7j9Pp_dN6PKM7Cf5qj9j7cFvLZM6xJ55ga-q6GzOue-XQ71GCdqOayypSgbhwguDo7eF2i9PDyZDqdbSxcdBtbrh1CH4FcYnR30SVNpWD_oGhPwZhsYFGQ4DVEBsH5kCEAJXCgaoJjLcvlmstKs48o8hEgYnYrGsrHe-0xxNobhmvryf-e9ibdKiUNrsrrok59Dluny54_1diI1smnSoKm7ymlKKqAZ1q7hed0rWXWKl_XXapOfo036R7XDaOC7VS-ieRxOiQ1gYYTQgnUthDdMV81NWv0_jVqW6OWfFKtfQjvZXyCYVc_uZUBps3ogYxOBwsycoGj2TAqSzpdLa3lEz1vV_PvumTq9CdK9afkDPH1-uOi1vc7X-R35XKveTMSocj68H5QDH0BChbL1xWYKvcHCT0YHduT6anOK9DcDvZefwm5xA5Jv6NuU861Gr7dxIPJXu6wSRdmAsDtoP-zLMk8NsX-yu1s4hYXtmSG_mKISK-8wacOgUQAXgllE5u3AVlHNsL1Mi5Pmxq-5PWtFrY-zsdfDxloJCbfsxf0xVy6ZKOCPxj__ktp7fGeWIKORmIMqG-ngZlIPwHagXF0Jwpgga50MQl06faCIXAI89WrhlbpxgVNtSW7lCaU5iSBmmF0Z2ClFkrJJUWRWrwamtOz4IIVqgEMzWG7-NRgJwLI9KMfO0cDsd6nTfS_I_OBCodS1EercdAnNqOCll3mosCqIHYOUAr3UMLIEt3yYGFid-rlTfcTNjAo13Zaii0-AX0xHGyFZrefcW3P-SSLsbT7p2ZyMo2oWND4qMhdgyEErc1drkDGYtPYYUWdGn-iepDjeD96NgtE14nhvgWK4TA6OKALTt77voWIc3rly1i3mdZh-sgBgd8tqls8bDoicwCCMvUC8TuxwbYFAjIt3vz2hHz_YBN93wa_OBDfuQ0Q_AuffDXJl5tVsVdtkCzNlE14xg4WHVQVfNCuAQeWw1SDnG-r9YYnWRTBdgnXtMA14cXdOcudqHd-2WB64pbl3FtOFwdnUwjNk3fbjLGxcEfupWz9JTLZ4Du-n3zi01ZIMIiWgH7lLTRSOMe1s55Ym0tiDvhMYhzAo8LFlqIA43FVtrxNC0STCU7QY5l8dG_Q-rdBQJJdh7LbFxEbZmWAA0DSMwbL_Cl2zpKAbSDTvypd0lRWsK0dZos2_YDEQr74riM4fm8c0ihIdFtIegqoW8Ap6bTM1GWcmd2CdwIt5kHucRKN72CF658uInvPITp3-1_DqEr1Lp7AKCKFWLgTmVEOMYftA7VGCtO7JHWzriId8zyHQ2RKBvY4E1wh2G6GtkXtACjB_nUkekgcx3FIdzAXb0FGApfYoDLj3zN0wH6dauLng7GdGkaagPV5wKjiF_yckwg-TDgYh8-LpaCWiO5waE5-5JyqenpS2fUGtZP8nnCHIdTV6GuT9-v10VsIXSsMcOMkag6qop-Tk0kxFjEfwf78gl_E0eXDOzsroN_ENgR7doFcf3FPXDbKslg7IqlU8jMtJb6ulOmNkSIGjgshvYHmfhLqv3J-l9CP4tYoZMHoH5xc7TI0UFbU-GtvgRsrzUYSwrv9nwY040YgIqkTvRyqCa9B91UkOeWrRPgW_rzN_Sc7VzgjSzxpRCeZhhdqNMrzlvp8oEebdxLvJ9ir0-S1JxB53_muUKFr8wn8LdZOuUbq5JBxlozeH_1iWzPoV0O2JXmZYJGp_IHvshVSrISQIcWtbqQxT-gjGBb0XjUHNJ8C8iMgpeQDd8oGdEpvExWTxqAasbP_RZHo7jO33pNyn3I2_joEMt3elLLBnzVMnDX-SFx3fe3r1MvJ9YBSZRnySPEd8U0Lv9oP5dtBaoaMHMMjKOeJVQoGFqsG0hwuDSze_mBFilcIdQiHgxvDXcmMUIy6BlmoU2SPicczTJ_dPm9DQGNr92jAVutOw6NgDf5kdXWKlhm_oNFzwi1_LEixlYvLSqcIMmCyYKk8mFirxDXwCOwIsqNSvSbm4_5ta-PuSt7uPj5MSO28JEwXizjpbQctC9qKrmEU-g0vPJB3ljirmiG8tShuWtcaWRuDacr2_cmqeKEwuoTwtQQzhqBGYSm_TBI6mZmzzQgJJ0rjqDnli21CVivHy9AHgM_oFN26EuyuiCdaVMPsfMFHopDd542lMIRLmLgRjsMu0o7sxCLAPcTMyuDWV0k28499lsSFdlwT-vyCLRhdsC3He5s-gapWEg3Zef2L7ovYy7IbTPjxLXQpdAt4LlRsZcRJnl-ZfglSBfUt8mm8Kni9EhDSGpFCRdlhKmAR2jQQ54egAunY1RPdklWiKbiLMk9WakpUwqDhwUWDG-yKI7f8HhZuL-3WKH3viGmE8SPf541OQskgHzHHNZuHDK047zzsjR8VHFodn7keojDPXIAwS3DdNJ-hHwGk8oDwe9YSRZSvv5lD7WFGdZG2HhS50HECffA",cRq: {ru: 'aHR0cHM6Ly9hcGkuc3RvcG1vZHJlcG9zdHMub3JnL3NpdGVzLmpzb24=',ra: 'TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEwNC4wLjAuMCBTYWZhcmkvNTM3LjM2',rm: 'R0VU',d: 'l10BBqjHQ6J73XQhZ4s5Kxq7xtcxfmHgsWT445YK+IIQ74kKTyI0imCASInznkabtsCGoduq8UhLa2mPlrwxTHTA9KErHo7fp4eItQx9A7p+vu6Zaj/Xh4myzvRcCocP5bOOnfVTVM0HzpmKxzqx26yaf87++II7KuH15JF03X+iFQvS4hfz6yRiXJJx6pPnzGfedIg+7gCQYnYYKFKsnEZ3Oxxnu9/WfYdtBy4veqZHfsnUXpcWBDf1jymaQoTT3cooppg9aGRY9d98i/NHI19bTx7jb1E25xLWOVnExkLvj6GzULNxRr3Tq0N9Up4CNmAAKF5/uDAVIC49gTnQI2YPsViarCvYUkYOOK2OZDVlux/81FLeoT5+A89Xem5bO+vQxGozwkXRBSrT+zPE88HiNOqqoPbdjXZbdhzlhO+/ke2516heWK+p47aOC3YxF8aY8ky1AOArazhI48vTDKtG2um4ED3DvdjD6FUgftu5eymyXneIhvzqeJScxubT',t: 'MTY5NzgxNjkyNC41MzEwMDA=',cT: Math.floor(Date.now() / 1000),m: '70mHCUIt+r3D3u61gUpakeNLL9Dujg8E0A3BV9Ti63g=',i1: 'XzS4K957oVSDWhNT/nm/OQ==',i2: 'hbf0dw0MtLjSo9ZjDnIoxg==',zh: '1GWYZQuJpwH8PFvf5Uyljhn3B/47FVR4Xvkav6kpykk=',uh: 't8s9M2Nkri6aDMvzDbDvv3tjAcBMqXGIfQOs+8qQ8kc=',hh: 'C0ngBxYnMs+PQW2EnRlnqpSVKxkMVHL/dduK39LffaA=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=8192682249015401';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/sites.json?__cf_chl_rt_tk=dljFysk7cAadUlg75wtmdChvFU9LSp_ViLbexJquVXQ-1697816924-0-gaNycGzNCvs" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>
```

</details>

**Comment by ACGaming** [comment]
Should be fixed with 394f5d6017844571121ddbaa6876bb0d43a7df93
