### ISSUE TITLE
Crash on modify file: `FileSystemException: �������`

### ISSUE THREAD

**Issue by Krutoy242** [TerraFirmaCraft-The-Final-Frontier/FileDirector#13]
I have file `twilighttweaks-1.12.2-v1.0.2.jar.jar` and want to disable / rename / remove it. Everything is crashing game loading with this error:

```less
[main/ERROR] [ModDirector/ConfigurationController[CORE]]: Failed to open a configuration for reading!
java.nio.file.FileSystemException: E:\mc_client\GDLuncher\instances\E2E-E\minecraft\mods\twilighttweaks-1.12.2-v1.0.2.jar.jar: ������� �� ����� �������� ������ � �����, ��� ��� ���� ���� ����� ������ ���������.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[?:1.8.0_352]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_352]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[?:1.8.0_352]
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269) ~[?:1.8.0_352]
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103) ~[?:1.8.0_352]
	at java.nio.file.Files.delete(Files.java:1126) ~[?:1.8.0_352]
	at net.jan.moddirector.core.configuration.ConfigurationController.handleModifyConfig(ConfigurationController.java:197) ~[ConfigurationController.class:1.8.0-SNAPSHOT]
```

I dont understand why i see `�` symbols but this may be related to the fact that i have Ru localized Windows.

Example of config:
```json
{
	"folder": "mods",
	"fileName": "twilighttweaks-1.12.2-v1.0.2.jar.jar",
	"delete": true
}
```

Also, it may be related that im using symlinks for minecraft folder.

[debug.log](https://github.com/TerraFirmaCraft-The-Final-Frontier/FileDirector/files/13367895/debug.log)

**Comment by Krutoy242** [comment]
Issue still actual 👀

**Comment by ACGaming** [comment]
Is this reproducible when not using symlinks? Please provide your File Director config files as well!

**Comment by Krutoy242** [comment]
I will try to reproduce it later.

**Comment by Krutoy242** [comment]
I think I will not test it. This would require me to install the twilighttweaks mod again and rearrange my dev environment to not using symlinks for a test, what require a lot of time.
Since I managed to avoid necessary of modifying file already, I think i will return to the issue when be required to rename or move something else.
