### ISSUE TITLE
CurseForge downloads cannot be extracted

### ISSUE THREAD

**Issue by BlueFeuer** [TerraFirmaCraft-The-Final-Frontier/FileDirector#14]
Cannot extract files downloaded from CurseForge via curse project / file ID.
Can extract them if downloaded via url as a workaround, such as; https://www.curseforge.com/api/v1/mods/(projectID)/files/(fileID)/download

But I'm not sure if that's the intended approach.

**Comment by SaxbyMod** [comment]
FYI this still seems to be a prevalent issue, as Im also receiving this with the following `JEI.curse.json`

```
{
    "addonId": 238222,
    "fileId": 5846804
}
```

Log Screams;
```
[13:06:09] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[13:06:09] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[13:06:09] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[13:06:09] [main/INFO]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[13:06:09] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_452, running on Windows 11:amd64:10.0, installed at C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\ModrinthApp\meta\java_versions\zulu8.86.0.25-ca-jre8.0.452-win_x64
[13:06:09] [main/INFO]: Searching C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\ModrinthApp\profiles\Minecards - Trading Card Game\mods for mods
[13:06:09] [main/INFO]: Loading tweaker net.jan.moddirector.launchwrapper.ModDirectorTweaker from !mod-director-launchwrapper-1.9.0.jar
[13:06:09] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:06:09] [main/INFO]: Loading tweak class name net.jan.moddirector.launchwrapper.ModDirectorTweaker
[13:06:10] [main/WARN]: Successfully replaced CA certificates with updated ones!
[13:06:10] [main/INFO]: Mod director loaded!
[13:06:10] [main/INFO]: ModDirector bootstrapped from Launchwrapper!
[13:06:10] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[13:06:10] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:06:10] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:06:10] [main/INFO]: Calling tweak class net.jan.moddirector.launchwrapper.ModDirectorTweaker
[13:06:10] [main/INFO]: Loading config config\mod-director\JEI.curse.json
[13:06:11] [main/ERROR]: An exception occurred while performing asynchronous work
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseReader(Ljava/io/Reader;)Lcom/google/gson/JsonElement;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_452]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_452]
	at net.jan.moddirector.core.ModDirector.awaitAll(ModDirector.java:259) [!mod-director-launchwrapper-1.9.0.jar:1.9.0]
	at net.jan.moddirector.core.ModDirector.activate(ModDirector.java:145) [!mod-director-launchwrapper-1.9.0.jar:1.9.0]
	at net.jan.moddirector.launchwrapper.ModDirectorTweaker.injectIntoClassLoader(ModDirectorTweaker.java:48) [!mod-director-launchwrapper-1.9.0.jar:1.9.0]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseReader(Ljava/io/Reader;)Lcom/google/gson/JsonElement;
	at net.jan.moddirector.core.configuration.type.CurseRemoteMod.queryInformation(CurseRemoteMod.java:82) ~[CurseRemoteMod.class:1.9.0]
	at net.jan.moddirector.core.manage.InstallController.lambda$createPreInstallTasks$0(InstallController.java:71) ~[InstallController.class:1.9.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_452]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_452]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_452]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_452]
[13:06:11] [main/ERROR]: ============================================================
[13:06:11] [main/ERROR]: Summary of 1 encountered errors:
[13:06:11] [main/ERROR]: An exception occurred while performing asynchronous work
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseReader(Ljava/io/Reader;)Lcom/google/gson/JsonElement;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_452]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_452]
	at net.jan.moddirector.core.ModDirector.awaitAll(ModDirector.java:259) [!mod-director-launchwrapper-1.9.0.jar:1.9.0]
	at net.jan.moddirector.core.ModDirector.activate(ModDirector.java:145) [!mod-director-launchwrapper-1.9.0.jar:1.9.0]
	at net.jan.moddirector.launchwrapper.ModDirectorTweaker.injectIntoClassLoader(ModDirectorTweaker.java:48) [!mod-director-launchwrapper-1.9.0.jar:1.9.0]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseReader(Ljava/io/Reader;)Lcom/google/gson/JsonElement;
	at net.jan.moddirector.core.configuration.type.CurseRemoteMod.queryInformation(CurseRemoteMod.java:82) ~[CurseRemoteMod.class:1.9.0]
	at net.jan.moddirector.core.manage.InstallController.lambda$createPreInstallTasks$0(InstallController.java:71) ~[InstallController.class:1.9.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_452]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_452]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_452]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_452]
[13:06:11] [main/ERROR]: ============================================================
```
