### ISSUE TITLE
File detection time

### ISSUE THREAD

**Issue by al-wei** [TerraFirmaCraft-The-Final-Frontier/FileDirector#23]
Sometimes, for some reason, it gets stuck.
I waited a long time and didn't even start loading the game.
![image](https://github.com/TerraFirmaCraft-The-Final-Frontier/FileDirector/assets/145486869/568e8dce-8e5b-4421-b86c-2eee4c9a06f0)

**Comment by ACGaming** [comment]
Can you share your log file when the freeze happens?

**Comment by al-wei** [comment]
I started the game a few times, and I think it's this.log file.

[23:10:12] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:10:12] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:10:12] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[23:10:12] [main/INFO]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[23:10:12] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_401, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre-1.8
[23:10:12] [main/INFO]: Searching E:\Minecraft\G-BFS\1122 - ����\.minecraft\mods for mods
[23:10:12] [main/INFO]: Loading tweaker net.jan.moddirector.launchwrapper.ModDirectorTweaker from !mod-director-launchwrapper-1.8.2-all.jar
[23:10:12] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:10:12] [main/INFO]: Loading tweak class name net.jan.moddirector.launchwrapper.ModDirectorTweaker
[23:10:12] [main/WARN]: Successfully replaced CA certificates with updated ones!
[23:10:12] [main/INFO]: Mod director loaded!
[23:10:12] [main/INFO]: ModDirector bootstrapped from Launchwrapper!
[23:10:12] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[23:10:12] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:10:12] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:10:12] [main/INFO]: Calling tweak class net.jan.moddirector.launchwrapper.ModDirectorTweaker
[23:10:12] [main/INFO]: Loading config config\mod-director\.bundle.json
[23:10:12] [main/INFO]: Loading config config\mod-director\optifine.url.json
[23:10:13] [main/ERROR]: Unable to launch
java.lang.NullPointerException: null
	at net.jan.moddirector.core.manage.select.InstallSelector.accept(InstallSelector.java:58) ~[!mod-director-launchwrapper-1.8.2-all.jar:1.8.2-SNAPSHOT]
	at net.jan.moddirector.core.ModDirector.activate(ModDirector.java:146) ~[!mod-director-launchwrapper-1.8.2-all.jar:1.8.2-SNAPSHOT]
	at net.jan.moddirector.launchwrapper.ModDirectorTweaker.injectIntoClassLoader(ModDirectorTweaker.java:48) ~[!mod-director-launchwrapper-1.8.2-all.jar:1.8.2-SNAPSHOT]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[23:10:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[23:10:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[23:10:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[23:10:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[23:10:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[23:10:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[23:10:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by phoenix-limited** [comment]
This is the same issue as mine, #21, is it a particular mod? What's you're mod list?

**Comment by al-wei** [comment]
> Can you share your log file when the freeze happens?

I don't know why the download crashed

https://gist.github.com/al-wei/b576f2dba8dac68377fa0079548ae9b2

**Comment by al-wei** [comment]
> > Can you share your log file when the freeze happens?
> 
> I don't know why the download crashed
> 
> https://gist.github.com/al-wei/b576f2dba8dac68377fa0079548ae9b2


The download timeout occurred again.
https://gist.github.com/al-wei/d44ce6f0f13dd81377e8e00b1a0cffa0
