### ISSUE TITLE
Failed to open connection to curse  

### ISSUE THREAD

**Issue by AlgorithmLX** [TerraFirmaCraft-The-Final-Frontier/FileDirector#7]
Hello! I have a problem, if i will try download a file from curseforge.

My `curse.bundle.json`:
```json
{
    "curse": [
        {
            "addonId": 243363,
            "fileId": 3099119
        }
    ]
}
```

Error log:
```
[22:27:41] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
 
[22:27:41] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
 
[22:27:41] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
 
[22:27:41] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
 
[22:27:41] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_371, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jdk-1.8\jre
 
[22:27:41] [main/INFO] [FML]: Searching C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\profiles\MTHB\mods for mods
 
[22:27:41] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in AcademyCraft-1.1.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:41] [main/WARN] [FML]: The coremod cn.lambdalib2.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
 
[22:27:41] [main/WARN] [FML]: The coremod CorePlugin (cn.lambdalib2.CorePlugin) is not signed!
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Aroma1997Core-1.12.2-2.0.0.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/WARN] [FML]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
 
[22:27:42] [main/INFO] [FML]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in botaniatweaks-1.9.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/WARN] [FML]: The coremod Botania Tweaks Core (quaternary.botaniatweaks.asm.BotaniaTweakerPlugin) is not signed!
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in ClientFixer-1.12.2-1.9.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/WARN] [FML]: The coremod ClientFixer (com.gamerforea.clientfixer.loader.CoreMod) is not signed!
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CreativeCore_v1.10.45_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/WARN] [FML]: The coremod com.creativemd.creativecore.core.CreativePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
 
[22:27:42] [main/WARN] [FML]: The coremod CreativePatchingLoader (com.creativemd.creativecore.core.CreativePatchingLoader) is not signed!
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-1.0.2.31.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/WARN] [FML]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
 
[22:27:42] [main/WARN] [FML]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in DummyCoreUnofficial-2.4.112.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/WARN] [FML]: The coremod DummyCore.ASM.DCLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
 
[22:27:42] [main/WARN] [FML]: The coremod DCLoadingPlugin (DummyCore.ASM.DCLoadingPlugin) is not signed!
 
[22:27:42] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from DynamicSurroundings-1.12.2-3.6.2.1.jar
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.11-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/WARN] [FML]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
 
[22:27:42] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in HammerLib-1.12.2-2.0.6.26.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
 
[22:27:42] [main/WARN] [FML]: The coremod com.creativemd.itemphysic.ItemPatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
 
[22:27:42] [main/WARN] [FML]: The coremod ItemPatchingLoader (com.creativemd.itemphysic.ItemPatchingLoader) is not signed!
 
[22:27:42] [main/WARN] [FML]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
 
[22:27:42] [main/WARN] [FML]: The coremod IvToolkit (ivorius.ivtoolkit.IvToolkitLoadingPlugin) is not signed!
 
[22:27:42] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from JustEnoughIDs-1.0.3-55.jar
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Mekanism-1.12.2-9.8.3.390.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/WARN] [FML]: The coremod mekanism.coremod.MekanismCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
 
[22:27:42] [main/WARN] [FML]: The coremod MekanismCoremod (mekanism.coremod.MekanismCoremod) is not signed!
 
[22:27:42] [main/WARN] [FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
 
[22:27:42] [main/WARN] [FML]: The coremod MicdoodlePlugin (micdoodle8.mods.miccore.MicdoodlePlugin) is not signed!
 
[22:27:42] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from MixinBootstrap-1.0.5.jar
 
[22:27:42] [main/INFO] [FML]: Loading tweaker net.jan.moddirector.launchwrapper.ModDirectorTweaker from mod-director-launchwrapper-1.7.0-SNAPSHOT-all.jar
 
[22:27:42] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_G5.jar
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in PerfectSpawn-MC1.12.2-2.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/WARN] [FML]: The coremod lumien.perfectspawn.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
 
[22:27:42] [main/WARN] [FML]: The coremod LoadingPlugin (lumien.perfectspawn.asm.LoadingPlugin) is not signed!
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/WARN] [FML]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in SmoothFont-mc1.12.2-2.1.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/WARN] [FML]: The coremod bre.smoothfont.asm.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
 
[22:27:42] [main/WARN] [FML]: The coremod CorePlugin (bre.smoothfont.asm.CorePlugin) is not signed!
 
[22:27:42] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from Surge-1.12.2-2.0.77.jar
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in TenshiLib-1.12.2-1.2.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/WARN] [FML]: The coremod TenshiCore (com.flemmli97.tenshilib.asm.ASMLoader) is not signed!
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in ThaumicAugmentation-1.12.2-2.0.13.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from VanillaFix-1.0.10-150.jar
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Xaeros_Minimap_21.3.0.2_Forge_1.12.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/WARN] [FML]: The coremod XaeroMinimapPlugin (xaero.common.core.XaeroMinimapPlugin) is not signed!
 
[22:27:42] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in XaerosWorldMap_1.12.0.2_Forge_1.12.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
 
[22:27:42] [main/WARN] [FML]: The coremod XaeroWorldMapPlugin (xaero.map.core.XaeroWorldMapPlugin) is not signed!
 
[22:27:42] [main/WARN] [FML]: The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
 
[22:27:42] [main/WARN] [FML]: The coremod IELoadingPlugin (blusunrize.immersiveengineering.common.asm.IELoadingPlugin) is not signed!
 
[22:27:42] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from phosphor-1.12.2-0.2.6+build50-universal.jar
 
[22:27:42] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
 
[22:27:42] [main/INFO] [LaunchWrapper]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
 
[22:27:42] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
 
[22:27:42] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/profiles/MTHB/mods/JustEnoughIDs-1.0.3-55.jar Service=LaunchWrapper Env=CLIENT
 
[22:27:43] [main/WARN] [FML]: The coremod JustEnoughIDs Extension Plugin (org.dimdev.jeid.JEIDLoadingPlugin) is not signed!
 
[22:27:43] [main/INFO] [JustEnoughIDs]: Initializing JustEnoughIDs core mixins
 
[22:27:43] [main/INFO] [mixin]: Compatibility level set to JAVA_8
 
[22:27:43] [main/INFO] [JustEnoughIDs]: Initializing JustEnoughIDs initialization mixins
 
[22:27:43] [main/INFO] [VanillaFix]: Initializing VanillaFix
 
[22:27:43] [main/INFO] [VanillaFix]: Initializing StacktraceDeobfuscator
 
[22:27:43] [main/INFO] [VanillaFix]: Found MCP method mappings: methods-stable_39.csv
 
[22:27:43] [main/INFO] [VanillaFix]: Done initializing StacktraceDeobfuscator
 
[22:27:43] [main/INFO] [VanillaFix]: Initializing Bug Fix Mixins
 
[22:27:43] [main/INFO] [VanillaFix]: Initializing Crash Fix Mixins
 
[22:27:43] [main/INFO] [VanillaFix]: Initializing Profiler Improvement Mixins
 
[22:27:43] [main/INFO] [VanillaFix]: Initializing Mod Support Mixins
 
[22:27:43] [main/WARN] [FML]: The coremod VanillaFixLoadingPlugin (org.dimdev.vanillafix.VanillaFixLoadingPlugin) is not signed!
 
[22:27:43] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
 
[22:27:43] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
 
[22:27:43] [main/INFO] [LaunchWrapper]: Loading tweak class name net.jan.moddirector.launchwrapper.ModDirectorTweaker
 
[22:27:43] [main/INFO] [ModDirector[CORE]]: Mod director loaded!
 
[22:27:43] [main/INFO] [ModDirector/Tweaker[Launchwrapper]]: ModDirector bootstrapped from Launchwrapper!
 
[22:27:43] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
 
[22:27:43] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
 
[22:27:43] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
 
[22:27:43] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
 
[22:27:43] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
 
[22:27:43] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
 
[22:27:43] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
 
[22:27:43] [main/INFO] [LaunchWrapper]: Calling tweak class net.jan.moddirector.launchwrapper.ModDirectorTweaker
 
[22:27:43] [main/INFO] [ModDirector/ConfigurationController[CORE]]: Loading config config\mod-director\curse.bundle.json
 
[22:27:44] [main/INFO] [ModDirector/ConfigurationController[CORE]]: Loading config config\mod-director\urls.bundle.json
 
[22:27:44] [pool-2-thread-1/ERROR] [ModDirector/InstallController[CORE]]: Failed to query information for 243363:3099119 from Curse
 
net.jan.moddirector.core.exception.ModDirectorException: Failed to open connection to curse
 
	at net.jan.moddirector.core.configuration.type.CurseRemoteMod.queryInformation(CurseRemoteMod.java:93) ~[CurseRemoteMod.class:1.7.0-SNAPSHOT]
 
	at net.jan.moddirector.core.manage.InstallController.lambda$createPreInstallTasks$0(InstallController.java:70) ~[InstallController.class:1.7.0-SNAPSHOT]
 
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_371]
 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_371]
 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_371]
 
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_371]
 
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.curse.tools/v1/cf/mods/243363/files/3099119
 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_371]
 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_371]
 
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_371]
 
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1964) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1959) ~[?:1.8.0_371]
 
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1958) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1528) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1504) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1502) ~[?:1.8.0_371]
 
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_371]
 
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1501) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_371]
 
	at net.jan.moddirector.core.util.WebClient.get(WebClient.java:58) ~[WebClient.class:1.7.0-SNAPSHOT]
 
	at net.jan.moddirector.core.configuration.type.CurseRemoteMod.queryInformation(CurseRemoteMod.java:80) ~[CurseRemoteMod.class:1.7.0-SNAPSHOT]
 
	... 5 more
 
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.curse.tools/v1/cf/mods/243363/files/3099119
 
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1914) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1504) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1502) ~[?:1.8.0_371]
 
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_371]
 
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1501) ~[?:1.8.0_371]
 
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352) ~[?:1.8.0_371]
 
	at net.jan.moddirector.core.util.WebClient.get(WebClient.java:24) ~[WebClient.class:1.7.0-SNAPSHOT]
 
	at net.jan.moddirector.core.configuration.type.CurseRemoteMod.queryInformation(CurseRemoteMod.java:80) ~[CurseRemoteMod.class:1.7.0-SNAPSHOT]
 
	... 5 more
 
[22:27:44] [main/ERROR] [ModDirector[CORE]]: ============================================================
 
[22:27:44] [main/ERROR] [ModDirector[CORE]]: Summary of 1 encountered errors:
 
[22:27:44] [main/ERROR] [ModDirector[CORE]]: Failed to query information for mod 243363:3099119 from Curse
 
net.jan.moddirector.core.exception.ModDirectorException: Failed to open connection to curse
 
	at net.jan.moddirector.core.configuration.type.CurseRemoteMod.queryInformation(CurseRemoteMod.java:93) ~[CurseRemoteMod.class:1.7.0-SNAPSHOT]
 
	at net.jan.moddirector.core.manage.InstallController.lambda$createPreInstallTasks$0(InstallController.java:70) ~[InstallController.class:1.7.0-SNAPSHOT]
 
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_371]
 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_371]
 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_371]
 
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_371]
 
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.curse.tools/v1/cf/mods/243363/files/3099119
 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_371]
 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_371]
 
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_371]
 
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1964) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1959) ~[?:1.8.0_371]
 
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1958) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1528) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1504) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1502) ~[?:1.8.0_371]
 
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_371]
 
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1501) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_371]
 
	at net.jan.moddirector.core.util.WebClient.get(WebClient.java:58) ~[WebClient.class:1.7.0-SNAPSHOT]
 
	at net.jan.moddirector.core.configuration.type.CurseRemoteMod.queryInformation(CurseRemoteMod.java:80) ~[CurseRemoteMod.class:1.7.0-SNAPSHOT]
 
	... 5 more
 
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.curse.tools/v1/cf/mods/243363/files/3099119
 
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1914) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1504) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1502) ~[?:1.8.0_371]
 
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_371]
 
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1501) ~[?:1.8.0_371]
 
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_371]
 
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352) ~[?:1.8.0_371]
 
	at net.jan.moddirector.core.util.WebClient.get(WebClient.java:24) ~[WebClient.class:1.7.0-SNAPSHOT]
 
	at net.jan.moddirector.core.configuration.type.CurseRemoteMod.queryInformation(CurseRemoteMod.java:80) ~[CurseRemoteMod.class:1.7.0-SNAPSHOT]
 
	... 5 more
 
[22:27:44] [main/ERROR] [ModDirector[CORE]]: ============================================================
 
[22:27:44] [main/ERROR] [LaunchWrapper]: Unable to launch
 
net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException: null
 
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49) ~[forge-1.12.2-14.23.5.2860.jar:?]
 
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761) ~[?:1.8.0_371]
 
	at java.lang.Runtime.exit(Runtime.java:101) ~[?:1.8.0_371]
 
	at java.lang.System.exit(System.java:985) ~[?:1.8.0_371]
 
	at net.jan.moddirector.core.ModDirector.errorExit(ModDirector.java:243) ~[mod-director-launchwrapper-1.7.0-SNAPSHOT-all.jar:1.7.0-SNAPSHOT]
 
	at net.jan.moddirector.core.ModDirector.activate(ModDirector.java:139) ~[mod-director-launchwrapper-1.7.0-SNAPSHOT-all.jar:1.7.0-SNAPSHOT]
 
	at net.jan.moddirector.launchwrapper.ModDirectorTweaker.injectIntoClassLoader(ModDirectorTweaker.java:48) ~[mod-director-launchwrapper-1.7.0-SNAPSHOT-all.jar:1.7.0-SNAPSHOT]
 
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
 
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
 
[22:27:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
 
[22:27:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
 
[22:27:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
 
[22:27:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:101)
 
[22:27:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:985)
 
[22:27:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
 
[22:27:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 
```

Addon ID `243363` - The Betweenlands Mod
File ID `3099119` - https://www.curseforge.com/minecraft/mc-mods/angry-pixel-the-betweenlands-mod/files/3099119

**Comment by ACGaming** [comment]
There is another crash when initially installing the mod but downloading itself works just fine for me, so sadly can‘t reproduce.

**Comment by AlgorithmLX** [comment]
> There is another crash when initially installing The Betweenlands but downloading itself works just fine for me, so sadly can‘t reproduce.

It's so strange

**Comment by AlgorithmLX** [comment]
Oh, I understood what the problem is. The problem is not fashion, but rather the blocking of my country. You can close the issue, as there is no bug
![Screenshot_2023-08-21-02-39-21-547_com android chrome](https://github.com/TerraFirmaCraft-The-Final-Frontier/FileDirector/assets/46783751/babd094c-f06e-47a7-aba6-2da4e60e9a23)
